authorname: "Hoang Nhan Ha"
draft: false

project:
  type: website
  output-dir: docs
  
  resources:
    - "img/**"
    - "assets/**"
    - "sitemap.xml"
    - "_redirects"
    - "teaching/pdf/**"
    - "googlec2a5501554a21911.html"  # Add this line

preview: 
  port: 22222
  browser: true
  watch-inputs: true
  navigate: true

metadata:
  title: "Hoang Nhan Ha"
  description: "PhD candidate in Accounting at UC3M"
# keywords: 
#   - Accounting
#   - PhD
#   - UC3M
#   - Ha Hoang Nhan
#   - textual analysis
#   - machine learning
#   - audit research

website:
  title: "Hoang Nhan Ha"
  site-url: https://hahoangnhan.github.io/
  # image: img/website_thumbnail.png
  
  repo-url: "https://github.com/hahoangnhan/hahoangnhan.github.io"
  repo-branch: gh-pages
  
  search: 
    location: navbar
    type: textbox
  
  navbar:
    pinned: true
    logo: img/letter-N-logo.png
    left:
      - text: Research
        href: research/index.qmd
      - text: Teaching
        href: teaching/index.qmd
      - text: CV
        href: cv/index.qmd
      # - text: Blog
      #   href: blog/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/ha_hoang_nhan
      - icon: github
        href: https://github.com/hahoangnhan
      - icon: linkedin
        href: https://www.linkedin.com/in/nhanhh/
      - icon: envelope
        aria-label: email
        href: "mailto:nha@emp.uc3m.es"
  
  page-footer: 
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} 2024 Hoang Nhan Ha</span>
      <span class="faux-block"><a href="https://github.com/hahoangnhan/hahoangnhan.github.io">{{< fa brands github >}} Source Code</a></span>
    # center: |
    #   <span class="faux-block"><a href="/impressum/index.html">Impressum</a></span>
    right: |
      <span class="faux-block"> Designed with {{< fa heart >}}</span>
      <span class="faux-block"> Built with <a href="https://quarto.org/">Quarto</a></span>
  
execute:
  freeze: auto
  
filters:
  - html/newpagelink.lua

format:
  html:
    include-in-header: html/seo.html
    fontsize: 1.1em
    theme: 
      - flatly
      - html/styles.scss
    toc: false
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai

sitemap: true
