---
title: Research
description: "y"
format: html
comments: false
toc: false
---

My research interests include <span style="color: #EE6A24;">*corporate disclosure and auditing*</span>, with a particular focus on their economic consequences. My current agenda examines on how corporate reporting and auditing navigate untraditional and emerging issues related to <span style="color: #EE6A24;">*technology and regulatory development*</span> to meet public demand for high-quality information. To support that, I apply cutting-edge data science techniques, such as <span style="color: #EE6A24;">*machine learning*</span> and <span style="color: #EE6A24;">*generative AI*</span>, to explore <span style="color: #EE6A24;">*novel databases*</span> and quantify <span style="color: #EE6A24;">*new research concepts*</span>.

## Does Auditor Communication Matter? The Role of Knowledge Compatibility {#knowlegde-compatibility}
<div style="text-align: right; color: #EE6A24; margin: 0;">
*(with Beatriz García Osma and Jun Nguyen&#42;)* 
</div>
<div style="text-align: right; color: #EE6A24;">
*(&#42;co-corresponding author)* 
</div>

> Auditors need to keep a high profile as thought leaders due to the knowledge-intensive and credence nature of the audit. However, little is known about how auditors signal their expertise to market targets beyond what can be inferred by their past experience (e.g., industry portfolio). To study the relationship between <span style="color: #EE6A24;">*auditor communication strategy*</span> and audit market dynamics and audit quality, I introduce the concept of <span style="color: #EE6A24;">*knowledge compatibility*</span>, which is the alignment between the knowledge auditors offer and that clients demand. I quantify it by the similarity between <span style="color: #EE6A24;">*audit firm podcasts*</span> and client forward-looking disclosure. I hypothesize and find that knowledge compatibility is positively associated with (i) <span style="color: #EE6A24;">*audit fees*</span>, (ii) the likelihood of <span style="color: #EE6A24;">*new auditor appointments*</span>, and (iii) <span style="color: #EE6A24;">*accounting quality*</span>. I also provide evidence on the credibility of communication and actual knowledge development by hiring activities. These findings highlight the importance of auditor communication and the role of knowledge compatibility to address the idiosyncratic needs of audit clients.

## Audit in the Dark: Auditor Responses to Risk in the Absence of Authoritative Guidance {#crypto-audit} 
<div style="text-align: right; color: #EE6A24; margin: 0;">
*(with Beatriz García Osma, Jun Nguyen&#42;, and W. Robert Knechel)* 
</div>
<div style="text-align: right; color: #EE6A24;">
*(&#42;co-corresponding author)* 
</div>


We explore how auditors address risk in the <span style="color: #EE6A24;">*absence of authoritative accounting and auditing guidance*</span>. In an ever-evolving technological landscape, auditors are confronted with challenges transcending traditional organizational boundaries, often <span style="color: #EE6A24;">*lacking knowledge about potential risks*</span> in an <span style="color: #EE6A24;">*uncertain environment*</span>. In particular, we focus on the uncertain environment surrounding the <span style="color: #EE6A24;">*cryptocurrency ecosystem*</span>, and construct and validate <span style="color: #EE6A24;">*a text-based measure*</span> of the level and nature of <span style="color: #EE6A24;">*client-level exposure to cryptocurrency risks*</span>. We find that an <span style="color: #EE6A24;">*audit firm's timely internal guidance*</span> when authoritative guidance is lacking significantly impacts <span style="color: #EE6A24;">*auditor behavior*</span>, resulting in <span style="color: #EE6A24;">*increased audit fees and CAM disclosures*</span> and a <span style="color: #EE6A24;">*reduction in going concern opinions*</span> for clients with cryptocurrency exposure. The issuance of <span style="color: #EE6A24;">*SEC's Staff Accounting Bulletin No.121*</span> facilitated the clarification of formal firm policies but does not fully eliminate the increase that follows the issuance of internal audit firm guidance. We also document <span style="color: #EE6A24;">*increased hiring of crypto specialists*</span> at the office level. Overall, our study contributes by providing evidence of <span style="color: #EE6A24;">*mechanisms through which auditors proactively address technological developments*</span> and new sources of <span style="color: #EE6A24;">*uncertainty and risk*</span>.


## Cybersecurity Commitment {#cyber-commit} 
<div style="text-align: right; color: #EE6A24;">
*(with Encarna Guillamon Saorin)* 
</div>
<div style="text-align: right; color: #EE6A24;">
*(corresponding author)* 
</div>

> We propose a concept of the firm proactive strategy in reporting and addressing cybersecurity risks as <span style="color: #EE6A24;">*cybersecurity commitment*</span>. We then <span style="color: #EE6A24;">*quantify*</span> cybersecurity commitment from the Management Discussion and Analysis (MD\&A) section of 10-K filings and examine its relations with <span style="color: #EE6A24;">*economic consequences*</span> and <span style="color: #EE6A24;">*market valuation*</span>. We also decompose the nature of commitment by detecting five main topics: corporate governance, physical and financial resources, technology, policy, and stakeholder engagement. Our results indicate that companies showing cybersecurity commitment are <span style="color: #EE6A24;">*less likely to experience data breaches*</span>, and this protective effect is particularly strong in companies with greater breach risks. Firms with higher levels of cybersecurity commitment will get <span style="color: #EE6A24;">*more favorable operating debt covenants*</span>. High-risk but non-breached firms benefit from showing a strong cybersecurity commitment, which <span style="color: #EE6A24;">*lessens market negative spillover*</span> during breach events in the industry. Overall, our results suggest that cybersecurity commitment helps firms to lessen breaches and is valued positively by capital providers.